import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Image from 'next/image'

export default function Aula() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.titleHome}>hello world!</h1>
      <div className={styles.layoutImg}>
        <Image 
          src="/MarvelLogo.svg"
          width='300px'
          height='300px'
          alt='icone next'
        />
        <div className={styles.back}>
      </div>
      </div>
    </div>
  )
}
