import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import Card from '../components/Card'

export default function Home({pokemons}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.titleHome}> Projeto de Api de pokemon </h1>
      <div className={styles.card}>
        {pokemons.map(pokemon => (
          <Card key={pokemon.id} pokemon={pokemon}>{pokemon.name}</Card>
        ))}
      </div>
    </>
  )
}

export async function getStaticProps(){
  const maxPokemons = 251
  const api = 'https://pokeapi.co/api/v2/pokemon/'

  const res = await fetch(`${api}/?limit=${maxPokemons}`)
  const data = await res.json()
  
  //add pokemon
  data.results.forEach((item, index)=>{
      item.id = index + 1
  })
  return {
      props:{
          pokemons: data.results
      }
  }
}